// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'auth.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `OwnedGamesResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GamesDownloader>>
abstract class GamesDownloader implements RustOpaqueInterface {
  ArcSession get session;

  set session(ArcSession session);

  Future<GogDbGameDetails> fetchGameDetails({required String gameId});

  Future<Uint64List> fetchOwnedGameIds();

  factory GamesDownloader({required Session session}) => RustLib.instance.api
      .crateApiGamesDownloaderGamesDownloaderNew(session: session);
}

class GogDbGameBuild {
  final String? datePublished;
  final int? generation;
  final String? link;

  const GogDbGameBuild({this.datePublished, this.generation, this.link});

  @override
  int get hashCode =>
      datePublished.hashCode ^ generation.hashCode ^ link.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GogDbGameBuild &&
          runtimeType == other.runtimeType &&
          datePublished == other.datePublished &&
          generation == other.generation &&
          link == other.link;
}

class GogDbGameDetails {
  final String? title;
  final String? imageBoxart;
  final String? productType;
  final List<GogDbGameBuild> builds;

  const GogDbGameDetails({
    this.title,
    this.imageBoxart,
    this.productType,
    required this.builds,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      imageBoxart.hashCode ^
      productType.hashCode ^
      builds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GogDbGameDetails &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          imageBoxart == other.imageBoxart &&
          productType == other.productType &&
          builds == other.builds;
}
