// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Session gogInitialize() => RustLib.instance.api.crateApiGogdlGogInitialize();

Auth gogGetAuth({required Session session}) =>
    RustLib.instance.api.crateApiGogdlGogGetAuth(session: session);

Future<GamesDownloader> gogGetDownloader({
  required Session session,
  required Auth auth,
}) => RustLib.instance.api.crateApiGogdlGogGetDownloader(
  session: session,
  auth: auth,
);

Future<User> gogGetUser({required Session session, required Auth auth}) =>
    RustLib.instance.api.crateApiGogdlGogGetUser(session: session, auth: auth);

Future<void> gogLogin({required Auth auth, required String sessionCode}) =>
    RustLib.instance.api.crateApiGogdlGogLogin(
      auth: auth,
      sessionCode: sessionCode,
    );

Future<Uint64List> gogGetOwnedGames({required User user}) =>
    RustLib.instance.api.crateApiGogdlGogGetOwnedGames(user: user);

Future<GogDbGameDetails> gogGetGameDetails({
  required GamesDownloader downloader,
  required String gameId,
}) => RustLib.instance.api.crateApiGogdlGogGetGameDetails(
  downloader: downloader,
  gameId: gameId,
);

String gogGetImageBoxart({required GogDbGameDetails gameDetails}) => RustLib
    .instance
    .api
    .crateApiGogdlGogGetImageBoxart(gameDetails: gameDetails);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Auth>>
abstract class Auth implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AuthError>>
abstract class AuthError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GamesDownloader>>
abstract class GamesDownloader implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GogDbGameDetails>>
abstract class GogDbGameDetails implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Session>>
abstract class Session implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SessionError>>
abstract class SessionError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<User>>
abstract class User implements RustOpaqueInterface {}
